### ISSUE TITLE
Need support of last solr version

### ISSUE THREAD

**Issue by Godevin** [lando/solr#6]
With the log4j security report (https://platform.sh/blog/2021/platformsh-protects-from-apache-log4j/) we need to test one of the last version of solr.

**Comment by labboy0276** [comment]
@Godevin So I have updated solr to allow for the new versiosn.  However, we aren't rolling a new release of Lando until Jan 7th.

If you need to test this now, I would suggest installing lando from source https://docs.lando.dev/basics/installation.html#from-source to test 8.11.
